# Generated by Django 5.2.5 on 2025-11-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_contribuyente',
            field=models.CharField(choices=[('PEQUEÑO', 'Pequeño Contribuyente'), ('MEDIANO', 'Mediano Contribuyente')], default='PEQUEÑO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.tipocliente'),
        ),
    ]
