# Generated by Django 5.2.5 on 2025-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
    ]
